emp/urls.py
from django.urls import path
from emp import views
app_name="emp"
urlpatterns = [
    path('',views.home,name="home"),
    path('add',views.add,name="add"),
    path('view',views.view,name="view"),

    path('detail/<int:i>',views.detail,name="detail"),
    path('edit/<int:a>',views.edit,name="edit"),
    path('delete/<int:p>',views.delete,name="delete"),
]

employee/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('emp.urls')),
    # path('users/',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/users/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

emp/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):

    name=models.CharField(max_length=20)
    age=models.IntegerField()
    address=models.CharField(max_length=20)
    email=models.CharField(max_length=20)
    image=models.ImageField(upload_to="images")


    def __str__(self):
        return self.name

emp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from emp.models import Employee


# Create your views here.
def home(request):
    context={'name':'anu','age':23}
    return render(request,'home.html',context)





def view(request):
    return render(request, 'view.html')


#
def add(request):
    if(request.method=="POST"):

        n=request.POST['n']
        a=request.POST['a']
        ad=request.POST['ad']
        e=request.POST['e']
        im=request.FILES['i']

        b=Employee.objects.create(name=n,age=a,address=ad,email=e,image=im)
        b.save()
        return view(request)
    return render(request,'add.html')

def view(request):
    k=Employee.objects.all()
    return render(request,'view.html',{'emp':k})

def detail(request,i):
    k=Employee.objects.get(id=i)
    return render(request,'detail.html',{'emp':k})

def edit(request,a):
    k=Employee.objects.get(id=a)
    if(request.method=="POST"):
        k.name=request.POST['n']
        k.age=request.POST['a']
        k.address=request.POST['ad']
        k.email=request.POST['e']
        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.image=request.FILES['i']

        k.save()
        return view(request)

    return render(request,'edit.html',{'emp':k})

def delete(request,p):
    k = Employee.objects.get(id=p)
    k.delete()
    return view(request)


# Create your views here.

templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>add books</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

       <div class="mb-3">
  <label class="form-label">name</label>
  <input type="text" class="form-control"  name="n" placeholder="Enter the employee name">
</div>
         <div class="mb-3">
  <label class="form-label">age</label>
  <input type="number" class="form-control"  name="a" placeholder="Enter the employee age">
</div>
          <div class="mb-3">
  <label class="form-label">address</label>
  <input type="text" class="form-control"  name="ad" placeholder="Enter the address of the employee">
</div>
           <div class="mb-3">
  <label class="form-label">email</label>
  <input type="email" class="form-control"  name="e" placeholder="Enter the employee email">
</div>

    <div class="mb-3">
  <label class="form-label">image</label>
  <input type="file" class="form-control"  name="i">
</div>
   <div class="mb-3">
       <input type="submit" value="ADD">
   </div>

</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container">
    <a class="navbar-brand" href="#">EMPLOYEE MANAGEMENT</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'emp:home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp:add' %}">add books</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'emp:view' %}">view books</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="">Logout</a>
        </li>


          <li class="nav-item">
          <a class="nav-link" href="">register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="">login</a>
        </li>




      </ul>
      <form  class="d-flex " role="search">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="s" aria-label="Search">
        <button class="btn text-light btn-outline-success btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card mb-3 mt-3 mx-auto" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4 me-6">
      <img src="{{emp.image.url}}" class="rounded-start p-3" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body text-success">

        <p class="card-text">name : {{emp.name}}</p>
        <p class="card-text">age: {{emp.age}}</p>
          <p class="card-text">address : {{emp.address}}</p>

      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>login</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

       <div class="mb-3">
  <label class="form-label">name</label>
  <input type="text" class="form-control"  name="n" value="{{emp.name}}" placeholder="Enter the name">
</div>
         <div class="mb-3">
  <label class="form-label">age</label>
  <input type="number" class="form-control"  name="a" value="{{emp.age}}" placeholder="Enter the age">
</div>
          <div class="mb-3">
  <label class="form-label">address</label>
  <input type="text" class="form-control"  name="ad" value="{{emp.address}}" placeholder="Enter the address">
</div>
           <div class="mb-3">
  <label class="form-label">email</label>
  <input type="email" class="form-control"  name="e" value="{{emp.email}}" placeholder="Enter the email">
</div>

    <div class="mb-3">
  <label class="form-label">image</label>
        <img src="{{emp.image.url}}">
  <input type="file" class="form-control"  name="i">
</div>


   <div class="mb-3">
       <input type="submit" value="ADD">
   </div>

</form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}




{% block content %}

<h2 class="text-center text-light mt-3">welcome anu</h2>


{% endblock %}

templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>view employee</h1>
<table class="table table-bordered bg-light">
    <tr>
        <th>COVER</th>

        <th>name</th>
        <th>age</th>
        <th>address</th>
        <th>email</th>

        <th>view</th>
        <th>edit</th>
        <th>delete</th>
    </tr>
    {% for i in emp %}
    <tr>
        <td><img src="{{i.image.url}}"></td>

        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.address}}</td>
        <td>{{i.email}}</td>

        <td><a href="{% url 'emp:detail' i.id %}" class="btn btn-success">view</a></td>
        <td><a href="{% url 'emp:edit' i.id %}" class="btn btn-success">edit</a></td>
        <td><a href="{% url 'emp:delete' i.id %}" class="btn btn-success">delete</a></td>



    </tr>
    {% endfor %}
</table>

{% endblock %}